Update collect_ips.yml

diff --git a/.github/workflows/collect_ips.yml b/.github/workflows/collect_ips.yml
--- a/.github/workflows/collect_ips.yml
+++ b/.github/workflows/collect_ips.yml
@@ -1,4 +1,4 @@
-name: Collect IPs and DNS
+name: Collect IPs 
 
 on:
   workflow_dispatch:  # 手动触发
@@ -22,7 +22,9 @@ jobs:
       run: pip install -r requirements.txt
 
     - name: Run the collect_ips script
-      run: python collect_ips.py
+      run: |
+        echo "Running collect_ips.py..."
+        python collect_ips.py || { echo "collect_ips.py failed"; exit 1; }
 
     - name: Commit and push changes
       run: |
